### ISSUE TITLE
Dodatkowe loga partnerów

### ISSUE THREAD

**Issue by MarcinKosinski** [SER-warsaw/SER-warsaw.github.io#2]
@EmilBuszylo czy mógłbyś z tej prezentacji wyciąć loga brakujących sponsorów/partnerów i dodać je do naszej nowej strony https://github.com/mi2-warsaw/SER/blob/master/histoRia/SER_Trzecie_Urodziny.pdf ?
Chodzi mi o ten slajd
![sponsorzy](https://cloud.githubusercontent.com/assets/6773454/23826652/04cb9e42-06a1-11e7-8d90-22ba54523047.png)

**Comment by EmilBuszylo** [comment]
Jutro będzie zrobione

**Comment by MarcinKosinski** [comment]
Dziękówka. Spokojnie takie rzeczy morzesz robić w ciągu tygodnia. Nie musisz tego robić od ręki w weekend : )
