### ISSUE TITLE
nowe logo sponsora

### ISSUE THREAD

**Issue by MarcinKosinski** [SER-warsaw/SER-warsaw.github.io#3]
@EmilBuszylo moglibyśmy dorzucić to logo sponsora do strony?
![7n logo jpg](https://cloud.githubusercontent.com/assets/6773454/25823859/a4fcb30a-343d-11e7-9971-77bfca55c1e4.jpg)

**Comment by EmilBuszylo** [comment]
Jutro późnym wieczorem wrzuce na strone
