### ISSUE TITLE
nie dziala sekcja organizatorow ani sponsorow

### ISSUE THREAD

**Issue by MarcinKosinski** [SER-warsaw/SER-warsaw.github.io#7]
![image](https://user-images.githubusercontent.com/6773454/34692794-a462ae82-f4c1-11e7-92f8-cee863ac9218.png)

**Comment by agosiewska** [comment]
Nie działa chyba tylko na chrome, na firefoxie jest ok.
![image](https://user-images.githubusercontent.com/18423383/34692973-4e65c810-f4c2-11e7-9574-12f98d85c795.png)

**Comment by MarcinKosinski** [comment]
@agosiewska zastanawiam sie czy moze to jest kwestia tego (podobnie bylo ze strona Why R?) https://github.com/whyRconf/whyRconf.github.io/commit/ca27de6abc1197159067e23d0a5c4b71ebcc7308

**Comment by MarcinKosinski** [comment]
https://github.com/SER-warsaw/SER-warsaw.github.io/commit/8404fc960f83f6a6a94683a513eeb795d820e25c

**Comment by MarcinKosinski** [comment]
Ta, ten sam problem. Rozwiazany
