### ISSUE TITLE
Akutalizacja liczb w `Informacje`

### ISSUE THREAD

**Issue by MarcinKosinski** [SER-warsaw/SER-warsaw.github.io#8]

**Comment by agosiewska** [comment]
@MarcinKosinski  zobacz, czy już wszystkie liczby się zgadzają
zmieniłam liczbę spotkań na 29
Społeczność entuzjastów na 1700 zgodnie z meetupem
dodałam jedną konferencję - WhyR?
i jeden maraton analizy danych - Hackathon przy WhyR?

**Comment by MarcinKosinski** [comment]
@agosiewska konferencje to chyba beda 2 - Why R? 2017 i eRum 2016, ale niby pomagamy przy Why R? 2018 wiec niech zostanie 3 :)

Patrze na hackathony - zespolowy miniMaraton analizy danych, hackathon przed Why R? i `jak oni glosowali` - to by bylo tez poprawnie, wedlug prezentacji Przemka. https://github.com/mi2-warsaw/SER/blob/master/histoRia/SER_Trzecie_Urodziny.pdf

Dzieki za poprawke 👍
